### ISSUE TITLE
Cannot have two different JPDB frequency dictionaries in yomitan at once 

### ISSUE THREAD

**Issue by SpeedPeruna** [Kuuuube/yomitan-dictionaries#1]
I'm trying to use the _JPDB v2.2 Frequency Kana (Recommended)_ dictionary for choosing whether to learn a word, and the _JPDB v2.2 Frequency Kana Display Only_ dictionary to sort the results in a better order, but when I try to import the other one, yomitan gives me an error "Dictionary JPDBv2㋕ is already imported, skipped it". 

Renaming the already imported dictionary did not solve the problem.

![Fri Nov  1 01:48:58 PM EET 2024](https://github.com/user-attachments/assets/f1705c7c-5af3-4df9-a3ec-8b26cad0dc78)

**Comment by Kuuuube** [comment]
They are intentionally named the same to keep the naming slim. You can unzip the dict, rename it in the index file, zip it, import.

**Comment by SpeedPeruna** [comment]
Thank you. This worked.
